### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'user' 

### ISSUE THREAD

**Issue by pawisoon** [n-elloco/django-active-users#5]
Hi,
I'm running django 2.1.5 and after adding `'active_users.middleware.ActiveUsersSessionMiddleware',` I get this error:

`    if request.user.id is not None:
AttributeError: 'WSGIRequest' object has no attribute 'user'
[30/May/2019 18:16:31] "GET / HTTP/1.1" 500 59`

My middleware settings: 

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'active_users.middleware.ActiveUsersSessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'whitenoise.middleware.WhiteNoiseMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'simple_history.middleware.HistoryRequestMiddleware',
]

Any idea why is that not working?

**Comment by n-elloco** [comment]
@pawisoon Put the middleware after 'django.contrib.auth.middleware.AuthenticationMiddleware'.
I will fix the README file
